### ISSUE TITLE
References from all the latex documents

### ISSUE THREAD

**Issue by PierreMarchand20** [hesstobi/atom-autocomplete-latex-references#6]
I have all my latex files in a git repository and I am using the `project-manager` package to get an "atom project" (or atom window in practice) by git repository. 

So, at the end, I have all my latex files in my "atom project" and I noticed that when I use `autocomplete-latex-references`, it looks for references through all my tex files, which is not really relevant since they are not all part of the same document. Would it be possible to look for references only in files related to the same document ? 

In the package `hyperclick-latex`, it only looks for references from latex files related to the same document, so I guess it is at least possible.

**Comment by werunom** [comment]
I have noticed the same. Instead of showing the references only of the current file, I am getting references from other documents too.

**Comment by hesstobi** [comment]
Yes this is how the package currently works. To fix this general it would need to have a root file detection and then follow `input` and `include` statements. This is already done a needed  other latex packages (like `hyperclick-latex`). Thus, it would be useful to implement a service package for this functionality. I will get in contact to the other developers.
As a quick bug fix, I can provide a config value to show only the labels of the current file. Would this help you?

**Comment by PierreMarchand20** [comment]
Thank you for your answer. I personally do not need it because my document is splitted in several files, so that I need to get references from the other tex files from my document. But it may be useful for others.

**Comment by werunom** [comment]
I would vote for including the labels of only the related documents. This would definitely be a neater design than the present situation since, as in my case for instance, there can be both related and independent documents in the projects. 

And moreover, getting all the labels as suggestions requires remembering the label-name given for the particular section/table/figure...which is an extra overhead task. If the labels provided would be minimum and relevant, finding the label would be quicker. 

If you want to include best of both the options, then probably providing the labels of the present doc higher-ranking would be nice. In this way, labels from the present document would appear at the beginning of the suggestions. 

Just thinking out loud and adding to the discussion :)
